Adding scripts to update xaml argument default value and handle SemVer strings.

diff --git a/.github/workflows/powershell-sample-scripts-test.yml b/.github/workflows/powershell-sample-scripts-test.yml
--- a/.github/workflows/powershell-sample-scripts-test.yml
+++ b/.github/workflows/powershell-sample-scripts-test.yml
@@ -16,12 +16,19 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Run Pester Tests
         run: |
+          env
           cd powershell
-          Invoke-Pester .\tests -Output Detailed
+          $result = Invoke-Pester .\tests -Output Detailed
+
+          # Check if the Pester tests failed
+          if ($result.FailedCount -gt 0) {
+            echo "Pester tests failed."
+            exit 1
+          }
 
   pester-test-ubuntu:
     name: Pester Test Runner on Ubuntu
@@ -29,8 +36,9 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Run Pester Tests
         run: |
-          pwsh -Command "cd powershell; Invoke-Pester ./tests -Output Detailed"
+          env
+          pwsh -Command 'cd powershell; Invoke-Pester ./tests -Output Detailed -CI'
